### PR TITLE
WIP: Pass ssl_context variable to trio

### PR DESCRIPTION
**Pull request by jmaroeder**
This adds functionality to the `ssl` kwarg when calling multio.open_connection with trio to support the same `ssl` parameter that curio uses.

Note that curio allows for passing a plain Python `SSLContext` in addition to the curio-specific `CurioSSLContext`, so this style should be encouraged.

I still need to test this with trio

### CODE REVIEW

**Comment by jmaroeder** [comment]
Addresses #15

**Comment by theelous3** [comment]
Seems reasonable. Holla when you've tested with trio. Linking test code would be handy dandy too for a quick review :)

**Comment by joernheissler** [comment]
Works with trio.
Why is Travis unhappy? Hope it's not related.

**Comment by joernheissler** [comment]
Note:
trio might need the `https_compatible=True` flag.
See https://trio.readthedocs.io/en/latest/reference-io.html#trio.ssl.SSLStream

I wasn't able to get asks to fail with a server that sends a complete response and then closes the socket. But perhaps there are real situations where it matters. E.g. when a connection is reused but the server closed the connection after the first request and a few seconds. I didn't test this.

**Pull request merged**
